services:
    jekyll:
        image: jekyll/jekyll:3.8
        command: /bin/sh -c /srv/jekyll/serve.sh
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
        environment:
            - JEKYLL_ENV=virtual
