services:
    jekyll:
        build:
            context: .
            secrets:
                - ca
        image: conan-blog
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll

secrets:
    ca:
        file: ${CA_CERT:-/dev/null}
